---
title       : "The emotion–facial expression link: Evidence from human and automatic expression recognition"
journal     : "Psychological Research"
manuscript  : "PRPF-D-20-00087"
bibliography: "../../manuscript/bib/manuscript_ref.bib"
output      : "papaja::revision_letter_pdf"
#output      : word_document
---

# Editor Comments

\RC{Dear Dr Tcherkassof,

We have received the reports from our advisers on your manuscript, "The emotion–facial expression link: Evidence from human and automatic expression recognition", which you submitted to Psychological Research.

Based on the advice received, I feel that your manuscript could be reconsidered for publication should you be prepared to incorporate major revisions. YOU ARE KINDLY REQUESTED TO ALSO CHECK THE WEBSITE FOR POSSIBLE REVIEWER ATTACHMENTS!

In order to submit your revised manuscript, please access the journal's website.

We look forward to receiving your revised manuscript before 25 Aug 2020.

With kind regards,
Ruth Krebs
Associate Editor
Psychological Research
}

Dear Dr. Ruth Krebs,

We would like thank you for taking the time to consider our manuscript for publication at _Psychological Research_, and the opportunity to resubmit a revised copy of this manuscript. We would also like to take this opportunity to express our thanks to the reviewers for the positive feedback and helpful comments for correction.

We believe such changes have resulted in an improved revised manuscript, which you will find uploaded alongside this document. The manuscript has been revised to address the reviewer comments, which are appended alongside our responses to this letter.

In the following we address the respect points made by both the editor and the reviewers.

# Reviewer \#1

## Main Points

\RC{The work of this article gives new insights about the connection of emotional self-reports and observer categorizations and automatic recognition of facial movements. The data are very interesting and this work should be published. But off course some things could be made better in the paper. The most important things are mainly in the methods and results section.}

## Method section

\RC{Page 15, line 57: in 2-3 or more lines should be described which kind of emotion inductions have been used for the data base.}

\RC{Page 16 line 39: why did the annotators only rate 232 of the 358 videos? And how have been the videos selected? Randomized selection or other criteria? Which? Why is not every video rated the same time? This especially is a point which looks not understandable.}

## Results section

\RC{Page 19 line 17 to 20: Which kind of correlation was computed here? A pearson correlation? It should be a point-biserial correlation as one of the two variables is dichotomous.}

\RC{Page 21 line 32: "expression intensity", where are expression intensity scores? Could you please bring the data into the paper?}

\RC{Page 21 line 40ff: Why should undetermined emotional states reveal that a 6-point Likert scale has a limit? What kind of limit? What would be better to do in future? Please explain in the text.}

## Minor points

\RC{Page 4 Line 44/45: one would not assume total agreement among all people based on basic emotion theory, so "totally" should be changed by another term like "mainly" or something similar.}  

\RC{Page 5 Line 16/17: Isn´t the point of Kraut and Jonston that according Basic Emotion Theory the smile is only a sign of expression of joy? So I would write: "that a smile is only the major".}

\RC{Page 5 line 58 ff: maybe smiling is not the right sign to be looked directly after winning a contest. Triumpf is usually exposed immediately after the contest and other emotions like joy or pride come a little later (see the work of Matsumoto and colleagues on that). So this argument from Crivelli et al. (2015) does not hold in that context.}

\RC{Page 18: line 56: "two-sided pearson correlation" probably means two-tailed t-tests of pearson-correlations, or not?}

\RC{Page 20 Line25: "60% and 80% accuracy"; please give a citation.}

\RC{Page 23 Line 56: what is correlated here (r=.22)? A correlation of two accuracies does not make sense in my mind. If yes, what are the units? Emotion categories, events or…???}

\RC{Page 31 line 9ff: I do not understand the point under secondly, automatic classifiers assume for every person unique facial expression for one emotion?? Did I understand that right? Could you explain that more in detail. So maybe in the methods section a more detailled description of the algorithm and how it works, would help…; as this is a psychological journal a principal description of the characteristics of the algorithm would help (that does not mean to explai}

# Reviewer \#2

\RC{1. The paper did not distinguish clearly between opinion and empirical evidence. Please revise.}

\RC{2. The paper's arguments must be built on an appropriate base of theory, concepts, or other ideas. It is recommended that the authors refer to Eigen Face Approach. }

\RC{3. The authors did not make clear emotion taxonomy. Ekman's basic set of emotions and Russell's circumflex model of affect are recommended to elaborate.}

\RC{4.  What is the significance of this study? must be explained with a sensible reason.}

\RC{5. The paper must contribute to a critical understanding of the issues.}

\RC{6. You're highly advised to show yourselves as authors while explaining theme of research in the paper. Keep the available references and at the same time let's the readers identify your own ideas and voice concerning what you cite in Introduction. }

\RC{7. The selection of the participants, to me, is vague.}

\RC{8. I wonder why the authors did not implement Principal Component Analysis.}

\RC{9. Discussion needs a deeper look. The plausible reasons behind obtaining these results are not satisfactory.  Moreover, the author/s did not discuss the validity and accuracy of the data. They did not state what their study adds to the body of literature. The last point is that in the discussion, the authors must compare/contrast their results with similar studies, mentioned in literature.}

\RC{10. It is recommended that authors consider APA, 7th edition in in-text citations. }

# References

\setlength{\leftskip}{0.4in}
\setlength{\parindent}{-0.4in}
